services:
  postgres:
    image: postgres:18.1
    container_name: postgres-db_job_crawler
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-job_crawler_db}
      POSTGRES_USER: ${POSTGRES_USER:-job_crawler_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supersecret}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-job_crawler_user} -d ${POSTGRES_DB:-job_crawler_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.6-rc1
    container_name: redis_job_crawler
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]

volumes:
  pgdata:
    name: postgres_data
  redis-data:
